apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.tmax.io
spec:
  group: tmax.io
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Template is the Schema for the templates API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TemplateSpec defines the desired state of Template
          properties:
            LongDescription:
              type: string
            UrlDescription:
              type: string
            imageUrl:
              type: string
            markDownDescription:
              type: string
            objectKinds:
              items:
                type: string
              type: array
            objects:
              items:
                properties:
                  kind:
                    type: string
                required:
                - kind
                type: object
              type: array
            operatorStartTime:
              type: string
            parameters:
              items:
                properties:
                  description:
                    type: string
                  displayName:
                    type: string
                  from:
                    type: string
                  generate:
                    type: string
                  name:
                    type: string
                  required:
                    type: boolean
                  value:
                    type: string
                  valueType:
                    type: string
                required:
                - name
                type: object
              type: array
            plans:
              items:
                type: object
              type: array
            provider:
              type: string
            recommend:
              type: boolean
            shortDescription:
              type: string
            tags:
              items:
                type: string
              type: array
          required:
          - parameters
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
